import type { Branch, Category, EmployeeKpiDaily, Item, Location, Role, SheetRecord, StockBalance, StockCount, StockCountItem, StockMovement, StockRequest, StockRequestItem, StoreItem, User, UserActivity, UserStats, XpTransaction } from "../models.js";
import { booleanCell, numberCell, stringCell } from "./sheets.js";

export const mapUser = (r: SheetRecord): User => ({ userId: stringCell(r.User_ID), username: stringCell(r.Username), passwordHash: stringCell(r.Password_Hash), displayName: stringCell(r.Display_Name), role: normalizeRole(r.Role), branchId: stringCell(r.Branch_ID), isActive: booleanCell(r.Is_Active), createdAt: stringCell(r.Created_At), avatarUrl: stringCell(r.Avatar_URL), lastLoginAt: stringCell(r.Last_Login_At), lastActiveAt: stringCell(r.Last_Active_At), updatedAt: stringCell(r.Updated_At) });
function normalizeRole(value: unknown): Role { const role = stringCell(value).toLowerCase(); if (role === "admin") return "owner"; return (["owner", "manager", "stock", "staff"] as const).includes(role as Role) ? role as Role : "staff"; }
export const mapBranch = (r: SheetRecord): Branch => ({ branchId: stringCell(r.Branch_ID), branchName: stringCell(r.Branch_Name), isActive: booleanCell(r.Is_Active), createdAt: stringCell(r.Created_At) });
export const mapCategory = (r: SheetRecord): Category => ({ categoryId: stringCell(r.Category_ID), categoryName: stringCell(r.Category_Name), sortOrder: numberCell(r.Sort_Order), isActive: booleanCell(r.Is_Active) });
export const mapItem = (r: SheetRecord): Item => ({ itemId: stringCell(r.Item_ID), itemName: stringCell(r.Item_Name), categoryId: stringCell(r.Category_ID), unit: stringCell(r.Unit), imageUrl: stringCell(r.Image_URL), description: stringCell(r.Description), isActive: booleanCell(r.Is_Active), createdAt: stringCell(r.Created_At) });
export const mapStoreItem = (r: SheetRecord): StoreItem => ({ storeItemId: stringCell(r.Store_Item_ID), branchId: stringCell(r.Branch_ID), itemId: stringCell(r.Item_ID), minQty: numberCell(r.Min_Qty), targetQty: numberCell(r.Target_Qty), defaultLocationId: stringCell(r.Default_Location_ID), allowRequest: booleanCell(r.Allow_Request), requireDailyCount: booleanCell(r.Require_Daily_Count), isActive: booleanCell(r.Is_Active) });
export const mapLocation = (r: SheetRecord): Location => ({ locationId: stringCell(r.Location_ID), locationName: stringCell(r.Location_Name), branchId: stringCell(r.Branch_ID), locationType: stringCell(r.Location_Type) as Location["locationType"], isActive: booleanCell(r.Is_Active) });
export const mapBalance = (r: SheetRecord): StockBalance => ({ balanceId: stringCell(r.Balance_ID), branchId: stringCell(r.Branch_ID), locationId: stringCell(r.Location_ID), itemId: stringCell(r.Item_ID), currentQty: numberCell(r.Current_Qty), updatedAt: stringCell(r.Updated_At) });
export const mapMovement = (r: SheetRecord): StockMovement => ({ movementId: stringCell(r.Movement_ID), movementDate: stringCell(r.Movement_Date), branchId: stringCell(r.Branch_ID), itemId: stringCell(r.Item_ID), movementType: stringCell(r.Movement_Type) as StockMovement["movementType"], fromLocationId: stringCell(r.From_Location_ID), toLocationId: stringCell(r.To_Location_ID), qty: numberCell(r.Qty), unit: stringCell(r.Unit), referenceType: stringCell(r.Reference_Type), referenceId: stringCell(r.Reference_ID), createdBy: stringCell(r.Created_By), note: stringCell(r.Note), createdAt: stringCell(r.Created_At) });
export const mapRequest = (r: SheetRecord): StockRequest => ({ requestId: stringCell(r.Request_ID), requestDate: stringCell(r.Request_Date), branchId: stringCell(r.Branch_ID), requestedBy: stringCell(r.Requested_By), requestStatus: stringCell(r.Request_Status) as StockRequest["requestStatus"], approvedBy: stringCell(r.Approved_By), completedAt: stringCell(r.Completed_At), note: stringCell(r.Note), createdAt: stringCell(r.Created_At) });
export const mapRequestItem = (r: SheetRecord): StockRequestItem => ({ requestItemId: stringCell(r.Request_Item_ID), requestId: stringCell(r.Request_ID), itemId: stringCell(r.Item_ID), requestedQty: numberCell(r.Requested_Qty), approvedQty: numberCell(r.Approved_Qty), issuedQty: numberCell(r.Issued_Qty), unit: stringCell(r.Unit), itemStatus: stringCell(r.Item_Status), note: stringCell(r.Note) });
export const mapCount = (r: SheetRecord): StockCount => ({ countId: stringCell(r.Count_ID), countDate: stringCell(r.Count_Date), branchId: stringCell(r.Branch_ID), locationId: stringCell(r.Location_ID), countRound: stringCell(r.Count_Round), countedBy: stringCell(r.Counted_By), countStatus: stringCell(r.Count_Status), note: stringCell(r.Note), createdAt: stringCell(r.Created_At) });
export const mapCountItem = (r: SheetRecord): StockCountItem => ({ countItemId: stringCell(r.Count_Item_ID), countId: stringCell(r.Count_ID), itemId: stringCell(r.Item_ID), systemQty: numberCell(r.System_Qty), countedQty: numberCell(r.Counted_Qty), varianceQty: numberCell(r.Variance_Qty), unit: stringCell(r.Unit), note: stringCell(r.Note) });
export const mapUserActivity = (r: SheetRecord): UserActivity => ({ activityId: stringCell(r.Activity_ID), activityDate: stringCell(r.Activity_Date), userId: stringCell(r.User_ID), branchId: stringCell(r.Branch_ID), action: stringCell(r.Action), entityType: stringCell(r.Entity_Type), entityId: stringCell(r.Entity_ID), result: stringCell(r.Result), detail: stringCell(r.Detail), metadataJson: stringCell(r.Metadata_JSON), createdAt: stringCell(r.Created_At) });
export const mapUserStats = (r: SheetRecord): UserStats => ({ userId: stringCell(r.User_ID), totalXp: numberCell(r.Total_XP), currentLevel: numberCell(r.Current_Level), currentLevelXp: numberCell(r.Current_Level_XP), nextLevelXp: numberCell(r.Next_Level_XP), currentStreak: numberCell(r.Current_Streak), longestStreak: numberCell(r.Longest_Streak), lastActiveDate: stringCell(r.Last_Active_Date), lastXpAt: stringCell(r.Last_XP_At), updatedAt: stringCell(r.Updated_At) });
export const mapXpTransaction = (r: SheetRecord): XpTransaction => ({ xpTransactionId: stringCell(r.XP_Transaction_ID), userId: stringCell(r.User_ID), activityId: stringCell(r.Activity_ID), xpAmount: numberCell(r.XP_Amount), reason: stringCell(r.Reason), entityType: stringCell(r.Entity_Type), entityId: stringCell(r.Entity_ID), createdAt: stringCell(r.Created_At) });
export const mapEmployeeKpiDaily = (r: SheetRecord): EmployeeKpiDaily => ({ kpiId: stringCell(r.KPI_ID), kpiDate: stringCell(r.KPI_Date), userId: stringCell(r.User_ID), branchId: stringCell(r.Branch_ID), assignedTasks: numberCell(r.Assigned_Tasks), completedTasks: numberCell(r.Completed_Tasks), onTimeTasks: numberCell(r.On_Time_Tasks), completionRate: numberCell(r.Completion_Rate), onTimeRate: numberCell(r.On_Time_Rate), stockCountTasks: numberCell(r.Stock_Count_Tasks), stockCountAccuracy: numberCell(r.Stock_Count_Accuracy), discrepancyCount: numberCell(r.Discrepancy_Count), requestsCreated: numberCell(r.Requests_Created), requestsApproved: numberCell(r.Requests_Approved), requestsRejected: numberCell(r.Requests_Rejected), requestsFulfilled: numberCell(r.Requests_Fulfilled), movementsCreated: numberCell(r.Movements_Created), activeMinutes: numberCell(r.Active_Minutes), loginCount: numberCell(r.Login_Count), updatedAt: stringCell(r.Updated_At) });

export const itemRecord = (v: Item): SheetRecord => ({ Item_ID: v.itemId, Item_Name: v.itemName, Category_ID: v.categoryId, Unit: v.unit, Image_URL: v.imageUrl, Description: v.description, Is_Active: v.isActive, Created_At: v.createdAt });
export const locationRecord = (v: Location): SheetRecord => ({ Location_ID: v.locationId, Location_Name: v.locationName, Branch_ID: v.branchId, Location_Type: v.locationType, Is_Active: v.isActive });
export const storeItemRecord = (v: StoreItem): SheetRecord => ({ Store_Item_ID: v.storeItemId, Branch_ID: v.branchId, Item_ID: v.itemId, Min_Qty: v.minQty, Target_Qty: v.targetQty, Default_Location_ID: v.defaultLocationId, Allow_Request: v.allowRequest, Require_Daily_Count: v.requireDailyCount, Is_Active: v.isActive });
export const balanceRecord = (v: StockBalance): SheetRecord => ({ Balance_ID: v.balanceId, Branch_ID: v.branchId, Location_ID: v.locationId, Item_ID: v.itemId, Current_Qty: v.currentQty, Updated_At: v.updatedAt });
export const movementRecord = (v: StockMovement): SheetRecord => ({ Movement_ID: v.movementId, Movement_Date: v.movementDate, Branch_ID: v.branchId, Item_ID: v.itemId, Movement_Type: v.movementType, From_Location_ID: v.fromLocationId, To_Location_ID: v.toLocationId, Qty: v.qty, Unit: v.unit, Reference_Type: v.referenceType, Reference_ID: v.referenceId, Created_By: v.createdBy, Note: v.note, Created_At: v.createdAt });
export const requestRecord = (v: StockRequest): SheetRecord => ({ Request_ID: v.requestId, Request_Date: v.requestDate, Branch_ID: v.branchId, Requested_By: v.requestedBy, Request_Status: v.requestStatus, Approved_By: v.approvedBy, Completed_At: v.completedAt, Note: v.note, Created_At: v.createdAt });
export const requestItemRecord = (v: StockRequestItem): SheetRecord => ({ Request_Item_ID: v.requestItemId, Request_ID: v.requestId, Item_ID: v.itemId, Requested_Qty: v.requestedQty, Approved_Qty: v.approvedQty, Issued_Qty: v.issuedQty, Unit: v.unit, Item_Status: v.itemStatus, Note: v.note });
export const countRecord = (v: StockCount): SheetRecord => ({ Count_ID: v.countId, Count_Date: v.countDate, Branch_ID: v.branchId, Location_ID: v.locationId, Count_Round: v.countRound, Counted_By: v.countedBy, Count_Status: v.countStatus, Note: v.note, Created_At: v.createdAt });
export const countItemRecord = (v: StockCountItem): SheetRecord => ({ Count_Item_ID: v.countItemId, Count_ID: v.countId, Item_ID: v.itemId, System_Qty: v.systemQty, Counted_Qty: v.countedQty, Variance_Qty: v.varianceQty, Unit: v.unit, Note: v.note });
export const userActivityRecord = (v: UserActivity): SheetRecord => ({ Activity_ID: v.activityId, Activity_Date: v.activityDate, User_ID: v.userId, Branch_ID: v.branchId, Action: v.action, Entity_Type: v.entityType, Entity_ID: v.entityId, Result: v.result, Detail: v.detail, Metadata_JSON: v.metadataJson, Created_At: v.createdAt });
export const userStatsRecord = (v: UserStats): SheetRecord => ({ User_ID: v.userId, Total_XP: v.totalXp, Current_Level: v.currentLevel, Current_Level_XP: v.currentLevelXp, Next_Level_XP: v.nextLevelXp, Current_Streak: v.currentStreak, Longest_Streak: v.longestStreak, Last_Active_Date: v.lastActiveDate, Last_XP_At: v.lastXpAt, Updated_At: v.updatedAt });
export const xpTransactionRecord = (v: XpTransaction): SheetRecord => ({ XP_Transaction_ID: v.xpTransactionId, User_ID: v.userId, Activity_ID: v.activityId, XP_Amount: v.xpAmount, Reason: v.reason, Entity_Type: v.entityType, Entity_ID: v.entityId, Created_At: v.createdAt });
export const employeeKpiDailyRecord = (v: EmployeeKpiDaily): SheetRecord => ({ KPI_ID: v.kpiId, KPI_Date: v.kpiDate, User_ID: v.userId, Branch_ID: v.branchId, Assigned_Tasks: v.assignedTasks, Completed_Tasks: v.completedTasks, On_Time_Tasks: v.onTimeTasks, Completion_Rate: v.completionRate, On_Time_Rate: v.onTimeRate, Stock_Count_Tasks: v.stockCountTasks, Stock_Count_Accuracy: v.stockCountAccuracy, Discrepancy_Count: v.discrepancyCount, Requests_Created: v.requestsCreated, Requests_Approved: v.requestsApproved, Requests_Rejected: v.requestsRejected, Requests_Fulfilled: v.requestsFulfilled, Movements_Created: v.movementsCreated, Active_Minutes: v.activeMinutes, Login_Count: v.loginCount, Updated_At: v.updatedAt });
