"use client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect, useMemo } from "react";
import { useFieldArray, useForm } from "react-hook-form";
import { z } from "zod";
import { ErrorBox, PageHeader } from "@/components/page-kit";
import { get, post } from "@/lib/api";
import type { Item, Location, StockBalance, StoreItem } from "@/lib/types";

const schema = z.object({ locationId: z.string().min(1), countRound: z.enum(["OPENING", "MIDDAY", "CLOSING", "ADHOC"]), note: z.string(), items: z.array(z.object({ itemId: z.string(), itemName: z.string(), unit: z.string(), systemQty: z.number(), countedQty: z.coerce.number().min(0), note: z.string() })).min(1) }); type Form = z.infer<typeof schema>;
export default function CountPage() {
  const client = useQueryClient(); const locations = useQuery({ queryKey: ["locations"], queryFn: () => get<Location[]>("/locations") }); const items = useQuery({ queryKey: ["items"], queryFn: () => get<Item[]>("/items") }); const store = useQuery({ queryKey: ["store-items"], queryFn: () => get<StoreItem[]>("/store-items") }); const balances = useQuery({ queryKey: ["balances"], queryFn: () => get<StockBalance[]>("/stock-balances") }); const form = useForm<Form>({ defaultValues: { locationId: "", countRound: "CLOSING", note: "", items: [] } }); const fields = useFieldArray({ control: form.control, name: "items" }); const locationId = form.watch("locationId");
  useEffect(() => { if (!items.data || !store.data || !locationId) return; fields.replace(store.data.filter((s) => s.isActive && s.requireDailyCount).flatMap((s) => { const item = items.data?.find((i) => i.itemId === s.itemId && i.isActive); if (!item) return []; const systemQty = balances.data?.find((b) => b.locationId === locationId && b.itemId === item.itemId)?.currentQty ?? 0; return [{ itemId: item.itemId, itemName: item.itemName, unit: item.unit, systemQty, countedQty: systemQty, note: "" }]; })); }, [locationId, items.data, store.data, balances.data]);
  const watched = form.watch("items"); const summary = useMemo(() => ({ equal: watched.filter((v) => v.countedQty === v.systemQty).length, over: watched.filter((v) => v.countedQty > v.systemQty).length, short: watched.filter((v) => v.countedQty < v.systemQty).length }), [watched]);
  const save = useMutation({ mutationFn: ({ values, status }: { values: Form; status: "DRAFT" | "COMPLETED" }) => post("/stock-counts", { locationId: values.locationId, countRound: values.countRound, status, note: values.note, items: values.items.map((v) => ({ itemId: v.itemId, countedQty: v.countedQty, unit: v.unit, note: v.note })) }), onSuccess: () => { client.invalidateQueries({ queryKey: ["balances"] }); client.invalidateQueries({ queryKey: ["counts"] }); } });
  const submit = (status: "DRAFT" | "COMPLETED") => form.handleSubmit((values) => { const parsed = schema.parse(values); if (status === "COMPLETED" && !window.confirm(`ยืนยันผล: ตรง ${summary.equal}, เกิน ${summary.over}, ขาด ${summary.short}`)) return; save.mutate({ values: parsed, status }); })();
  return <><PageHeader eyebrow="Cycle count" title="นับสต๊อก" description="กรอกยอดจริงทั้งหมดในหน้าเดียว ระบบสร้าง Adjustment เมื่อยืนยันเสร็จ" /><div className="mb-5 grid gap-3 sm:grid-cols-3"><select className="field" {...form.register("locationId")}><option value="">เลือกตำแหน่ง</option>{locations.data?.filter((v) => v.isActive).map((v) => <option key={v.locationId} value={v.locationId}>{v.locationName}</option>)}</select><select className="field" {...form.register("countRound")}><option>OPENING</option><option>MIDDAY</option><option>CLOSING</option><option>ADHOC</option></select><input className="field" placeholder="หมายเหตุ" {...form.register("note")} /></div><div className="mb-4 grid grid-cols-3 gap-3">{[["ตรงกัน", summary.equal], ["เกิน", summary.over], ["ขาด", summary.short]].map(([label, value]) => <div className="border border-black bg-white p-3 text-center" key={String(label)}><p className="text-xs">{label}</p><p className="text-2xl font-black">{value}</p></div>)}</div>
    {!locationId ? <p className="border border-dashed p-8 text-center">เลือกตำแหน่งเพื่อเริ่มนับ</p> : !fields.fields.length ? <p className="border border-dashed p-8 text-center">ไม่มีรายการที่ตั้งค่า Require Daily Count</p> : <div className="space-y-2">{fields.fields.map((field, index) => <div className="grid items-center gap-2 border border-black bg-white p-3 sm:grid-cols-[1fr_110px_140px_1fr]" key={field.id}><div><p className="font-bold">{field.itemName}</p><p className="text-xs text-zinc-500">ระบบ {field.systemQty} {field.unit}</p></div><p className={`font-black ${(watched[index]?.countedQty ?? 0) - field.systemQty < 0 ? "text-red-600" : ""}`}>ต่าง {(watched[index]?.countedQty ?? 0) - field.systemQty}</p><input className="field" aria-label={`นับ ${field.itemName}`} inputMode="decimal" type="number" min="0" step="0.01" {...form.register(`items.${index}.countedQty`)} /><input className="field" placeholder="หมายเหตุ" {...form.register(`items.${index}.note`)} /></div>)}</div>}{save.error && <div className="mt-4"><ErrorBox error={save.error} /></div>}<div className="mt-5 flex gap-3"><button className="btn-secondary" disabled={save.isPending} onClick={() => submit("DRAFT")}>บันทึก Draft</button><button className="btn-primary" disabled={save.isPending} onClick={() => submit("COMPLETED")}>ยืนยันนับเสร็จ</button></div>
  </>;
}
