"use client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useParams } from "next/navigation";
import { useState } from "react";
import { Badge, ErrorBox, PageHeader } from "@/components/page-kit";
import { get, post } from "@/lib/api";
import type { Location, SessionUser, StockRequest } from "@/lib/types";

export default function RequestDetailPage() {
  const id = String(useParams().requestId); const client = useQueryClient(); const me = useQuery({ queryKey: ["me"], queryFn: () => get<SessionUser>("/auth/me") }); const query = useQuery({ queryKey: ["request", id], queryFn: () => get<StockRequest>(`/stock-requests/${id}`) }); const locations = useQuery({ queryKey: ["locations"], queryFn: () => get<Location[]>("/locations") }); const [approved, setApproved] = useState<Record<string, number>>({}); const [issued, setIssued] = useState<Record<string, number>>({}); const [from, setFrom] = useState("");
  const action = useMutation({ mutationFn: ({ path, body }: { path: string; body?: unknown }) => post(`/stock-requests/${id}/${path}`, body), onSuccess: () => { client.invalidateQueries({ queryKey: ["request", id] }); client.invalidateQueries({ queryKey: ["requests"] }); } });
  if (query.isError) return <ErrorBox error={query.error} />; if (!query.data) return <p>กำลังโหลด...</p>; const value = query.data; const canManage = me.data && me.data.role !== "staff";
  return <><PageHeader eyebrow="Request detail" title={value.requestId} description={`${value.requestDate} · ผู้ขอ ${value.requester?.displayName || value.requester?.username || value.requestedBy}`} actions={<Badge tone={value.requestStatus === "COMPLETED" ? "success" : "warning"}>{value.requestStatus}</Badge>} />
    <div className="overflow-x-auto border border-black bg-white"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-black text-white"><tr><th className="p-3">สินค้า</th><th>ขอ</th><th>อนุมัติ</th><th>จ่ายแล้ว</th><th>จ่ายเพิ่ม</th><th>สถานะ</th></tr></thead><tbody>{value.items?.map((item) => <tr key={item.requestItemId} className="border-t"><td className="p-3 font-bold">{item.item?.itemName || item.itemId}</td><td>{item.requestedQty} {item.unit}</td><td>{canManage && value.requestStatus === "PENDING" ? <input className="field w-24" type="number" min="0" max={item.requestedQty} value={approved[item.requestItemId] ?? item.requestedQty} onChange={(e) => setApproved({ ...approved, [item.requestItemId]: Number(e.target.value) })} /> : item.approvedQty}</td><td>{item.issuedQty}</td><td>{canManage && ["APPROVED", "PARTIAL"].includes(value.requestStatus) ? <input className="field w-24" type="number" min="0" max={(item.approvedQty || item.requestedQty) - item.issuedQty} value={issued[item.requestItemId] ?? 0} onChange={(e) => setIssued({ ...issued, [item.requestItemId]: Number(e.target.value) })} /> : "–"}</td><td>{item.itemStatus}</td></tr>)}</tbody></table></div>
    {action.error && <div className="mt-4"><ErrorBox error={action.error} /></div>}<div className="mt-5 flex flex-wrap gap-3">{canManage && value.requestStatus === "PENDING" && <><button className="btn-primary" onClick={() => action.mutate({ path: "approve", body: { items: value.items?.map((v) => ({ requestItemId: v.requestItemId, approvedQty: approved[v.requestItemId] ?? v.requestedQty })) } })}>อนุมัติ</button><button className="btn-secondary" onClick={() => action.mutate({ path: "reject" })}>ปฏิเสธ</button></>}{canManage && ["APPROVED", "PARTIAL"].includes(value.requestStatus) && <><select className="field max-w-xs" value={from} onChange={(e) => setFrom(e.target.value)}><option value="">คลัง WAREHOUSE อัตโนมัติ</option>{locations.data?.filter((v) => v.locationType === "WAREHOUSE" && v.isActive).map((v) => <option value={v.locationId} key={v.locationId}>{v.locationName}</option>)}</select><button className="btn-primary" onClick={() => action.mutate({ path: "issue", body: { items: value.items?.map((v) => ({ requestItemId: v.requestItemId, qty: issued[v.requestItemId] ?? 0, fromLocationId: from || undefined })) } })}>ยืนยันการจ่าย</button></>}{!canManage && value.requestStatus === "PENDING" && <button className="btn-secondary" onClick={() => action.mutate({ path: "cancel" })}>ยกเลิกคำขอ</button>}</div>
  </>;
}
