"use client";
import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { get, patch, post } from "@/lib/api";
import type { Category, Item } from "@/lib/types";
import { ProductImage } from "@/components/product-image";
import { Empty, ErrorBox, PageHeader } from "@/components/page-kit";

const schema = z.object({ itemName: z.string().min(1, "กรุณากรอกชื่อ"), categoryId: z.string().min(1), unit: z.string().min(1), imageUrl: z.string(), description: z.string(), isActive: z.boolean() });
type Form = z.infer<typeof schema>;
const defaults: Form = { itemName: "", categoryId: "", unit: "", imageUrl: "", description: "", isActive: true };

export default function ItemsPage() {
  const client = useQueryClient(); const [search, setSearch] = useState(""); const [category, setCategory] = useState(""); const [editing, setEditing] = useState<Item | null>(null); const [showForm, setShowForm] = useState(false); const [view, setView] = useState<"cards" | "table">("cards");
  const items = useQuery({ queryKey: ["items"], queryFn: () => get<Item[]>("/items") }); const categories = useQuery({ queryKey: ["categories"], queryFn: () => get<Category[]>("/categories") });
  const form = useForm<Form>({ resolver: zodResolver(schema), defaultValues: defaults });
  const save = useMutation({ mutationFn: (value: Form) => editing ? patch<Item>(`/items/${editing.itemId}`, value) : post<Item>("/items", value), onSuccess: () => { client.invalidateQueries({ queryKey: ["items"] }); setShowForm(false); setEditing(null); form.reset(defaults); } });
  const filtered = useMemo(() => (items.data ?? []).filter((v) => v.itemName.toLowerCase().includes(search.toLowerCase()) && (!category || v.categoryId === category)), [items.data, search, category]);
  const edit = (item: Item) => { setEditing(item); setShowForm(true); form.reset({ itemName: item.itemName, categoryId: item.categoryId, unit: item.unit, imageUrl: item.imageUrl, description: item.description, isActive: item.isActive }); };
  return <><PageHeader eyebrow="Master data" title="ตั้งค่าไอเทม" description="ปิดไอเทมแทนการลบข้อมูลจริง รูป local วางที่ apps/web/public/images/items/" actions={<button className="btn-primary" onClick={() => { setEditing(null); form.reset(defaults); setShowForm(true); }}>+ เพิ่มไอเทม</button>} />
    <div className="mb-5 grid gap-3 sm:grid-cols-[1fr_220px_auto]"><input className="field" placeholder="ค้นหาชื่อสินค้า" value={search} onChange={(e) => setSearch(e.target.value)} /><select className="field" value={category} onChange={(e) => setCategory(e.target.value)}><option value="">ทุกหมวดหมู่</option>{categories.data?.map((v) => <option key={v.categoryId} value={v.categoryId}>{v.categoryName}</option>)}</select><button className="btn-secondary" onClick={() => setView(view === "cards" ? "table" : "cards")}>{view === "cards" ? "มุมมองตาราง" : "มุมมองการ์ด"}</button></div>
    {items.isError ? <ErrorBox error={items.error} /> : !filtered.length ? <Empty text="ยังไม่มีไอเทม" /> : view === "cards" ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{filtered.map((item) => <article key={item.itemId} className="overflow-hidden border border-black bg-white"><div className="grid grid-cols-[110px_1fr]"><ProductImage src={item.imageUrl} name={item.itemName} /><div className="p-4"><p className="font-black">{item.itemName}</p><p className="text-sm text-zinc-500">{item.unit} · {categories.data?.find((v) => v.categoryId === item.categoryId)?.categoryName}</p><p className={`mt-2 text-xs font-bold ${item.isActive ? "text-emerald-700" : "text-red-700"}`}>{item.isActive ? "เปิดใช้งาน" : "ปิดใช้งาน"}</p><button className="mt-3 text-sm font-bold underline" onClick={() => edit(item)}>แก้ไข</button></div></div></article>)}</div> : <div className="overflow-x-auto border border-black bg-white"><table className="w-full text-left text-sm"><thead className="bg-black text-white"><tr><th className="p-3">ชื่อ</th><th>หมวด</th><th>หน่วย</th><th>สถานะ</th><th /></tr></thead><tbody>{filtered.map((item) => <tr className="border-t" key={item.itemId}><td className="p-3 font-bold">{item.itemName}</td><td>{categories.data?.find((v) => v.categoryId === item.categoryId)?.categoryName}</td><td>{item.unit}</td><td>{item.isActive ? "Active" : "Inactive"}</td><td><button className="underline" onClick={() => edit(item)}>แก้</button></td></tr>)}</tbody></table></div>}
    {showForm && <div className="fixed inset-0 z-50 grid place-items-end bg-black/50 p-0 sm:place-items-center sm:p-4"><form onSubmit={form.handleSubmit((v) => save.mutate(v))} className="max-h-[90vh] w-full overflow-auto bg-white p-5 sm:max-w-lg sm:border sm:border-black"><h2 className="mb-5 text-2xl font-black">{editing ? "แก้ไขไอเทม" : "เพิ่มไอเทม"}</h2><div className="space-y-4"><Field label="ชื่อ"><input className="field" {...form.register("itemName")} /></Field><Field label="หมวดหมู่"><select className="field" {...form.register("categoryId")}><option value="">เลือกหมวด</option>{categories.data?.map((v) => <option key={v.categoryId} value={v.categoryId}>{v.categoryName}</option>)}</select></Field><Field label="หน่วย"><input className="field" {...form.register("unit")} /></Field><Field label="Image URL"><input className="field" placeholder="/images/items/water.webp" {...form.register("imageUrl")} /></Field><Field label="คำอธิบาย"><textarea className="field" {...form.register("description")} /></Field><label className="flex gap-3"><input type="checkbox" {...form.register("isActive")} /> เปิดใช้งาน</label>{save.error && <ErrorBox error={save.error} />}</div><div className="mt-6 flex gap-3"><button className="btn-primary" disabled={save.isPending}>บันทึก</button><button type="button" className="btn-secondary" onClick={() => setShowForm(false)}>ยกเลิก</button></div></form></div>}
  </>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-bold">{label}<div className="mt-1">{children}</div></label>; }
