"use client";
import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { get, patch, post } from "@/lib/api";
import type { Location } from "@/lib/types";
import { EmptyState, ErrorBox, FormField, GameButton, GameCard, GamePanel, PageHeader, StatusBadge } from "@/components/page-kit";

const schema = z.object({ locationName: z.string().min(1), locationType: z.enum(["WAREHOUSE", "FRIDGE", "KITCHEN", "COUNTER", "STORAGE"]), isActive: z.boolean() }); type Form = z.infer<typeof schema>;
export default function LocationsPage() {
  const client = useQueryClient(); const query = useQuery({ queryKey: ["locations"], queryFn: () => get<Location[]>("/locations") }); const form = useForm<Form>({ resolver: zodResolver(schema), defaultValues: { locationName: "", locationType: "WAREHOUSE", isActive: true } });
  const save = useMutation({ mutationFn: (v: Form & { locationId?: string }) => v.locationId ? patch(`/locations/${v.locationId}`, v) : post("/locations", v), onSuccess: () => { client.invalidateQueries({ queryKey: ["locations"] }); form.reset({ locationName: "", locationType: "WAREHOUSE", isActive: true }); } });
  return <><PageHeader eyebrow="Store setup" title="ตำแหน่งจัดเก็บ" description="สร้างคลัง ตู้เย็น ครัว เคาน์เตอร์ และพื้นที่เก็บของของสาขา" /><div className="grid gap-6 lg:grid-cols-[360px_1fr]"><GamePanel className="h-fit p-5"><form onSubmit={form.handleSubmit((v) => save.mutate(v))}><h2 className="mb-4 text-xl font-black text-[var(--color-game-brown)]">เพิ่มตำแหน่ง</h2><div className="space-y-4"><FormField label="ชื่อตำแหน่ง"><input placeholder="ชื่อตำแหน่ง" {...form.register("locationName")} /></FormField><FormField label="ประเภทตำแหน่ง"><select {...form.register("locationType")}>{["WAREHOUSE", "FRIDGE", "KITCHEN", "COUNTER", "STORAGE"].map((v) => <option key={v}>{v}</option>)}</select></FormField><label className="flex items-center gap-2 text-sm font-bold text-[var(--color-game-ink)]"><input type="checkbox" {...form.register("isActive")} /> เปิดใช้งาน</label>{save.error && <ErrorBox error={save.error} />}<GameButton type="submit" className="w-full" disabled={save.isPending}>บันทึก</GameButton></div></form></GamePanel><section>{query.isError ? <ErrorBox error={query.error} /> : !query.data?.length ? <EmptyState title="ยังไม่มีตำแหน่ง" description="เพิ่มตำแหน่งจัดเก็บจากแบบฟอร์มด้านข้าง" /> : <div className="grid gap-3 sm:grid-cols-2">{query.data.map((v) => <GameCard className="p-4" key={v.locationId}><div className="flex justify-between gap-3"><div><p className="font-black text-[var(--color-game-brown)]">{v.locationName}</p><p className="mt-1 text-sm text-[var(--color-game-muted)]">{v.locationType}</p><StatusBadge className="mt-3" tone={v.isActive ? "success" : "neutral"}>{v.isActive ? "ACTIVE" : "INACTIVE"}</StatusBadge></div><label className="flex items-start gap-2 text-xs font-bold"><input type="checkbox" checked={v.isActive} onChange={() => save.mutate({ locationId: v.locationId, locationName: v.locationName, locationType: v.locationType as Form["locationType"], isActive: !v.isActive })} /> {v.isActive ? "ON" : "OFF"}</label></div></GameCard>)}</div>}</section></div></>;
}
