"use client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect, useMemo, useState } from "react";
import { get, put } from "@/lib/api";
import type { Category, Item, Location, SessionUser, StoreItem } from "@/lib/types";
import { ProductImage } from "@/components/product-image";
import { ErrorBox, PageHeader } from "@/components/page-kit";

export default function StoreItemsPage() {
  const client = useQueryClient(); const me = useQuery({ queryKey: ["me"], queryFn: () => get<SessionUser>("/auth/me") }); const items = useQuery({ queryKey: ["items"], queryFn: () => get<Item[]>("/items") }); const categories = useQuery({ queryKey: ["categories"], queryFn: () => get<Category[]>("/categories") }); const locations = useQuery({ queryKey: ["locations"], queryFn: () => get<Location[]>("/locations") }); const store = useQuery({ queryKey: ["store-items"], queryFn: () => get<StoreItem[]>("/store-items") });
  const [draft, setDraft] = useState<Record<string, StoreItem>>({}); const [search, setSearch] = useState(""); const [category, setCategory] = useState(""); const [selectedOnly, setSelectedOnly] = useState(false);
  useEffect(() => { if (store.data) setDraft(Object.fromEntries(store.data.map((v) => [v.itemId, v]))); }, [store.data]);
  const update = (itemId: string, patch: Partial<StoreItem>) => setDraft((current) => { const base: StoreItem = { storeItemId: "", branchId: me.data?.branchId ?? "", itemId, minQty: 0, targetQty: 0, defaultLocationId: "", allowRequest: true, requireDailyCount: false, isActive: true }; return { ...current, [itemId]: { ...base, ...(current[itemId] ?? {}), ...patch } }; });
  const save = useMutation({ mutationFn: () => put("/store-items/batch", { branchId: me.data?.branchId, items: Object.values(draft) }), onSuccess: () => client.invalidateQueries({ queryKey: ["store-items"] }) });
  const filtered = useMemo(() => (items.data ?? []).filter((v) => v.itemName.toLowerCase().includes(search.toLowerCase()) && (!category || v.categoryId === category) && (!selectedOnly || draft[v.itemId]?.isActive)), [items.data, search, category, selectedOnly, draft]);
  return <><PageHeader eyebrow="Branch assortment" title="ไอเทมที่สาขาใช้" description="เลือกและตั้งค่าหลายรายการ แล้วบันทึกครั้งเดียว" actions={<button className="btn-primary" disabled={save.isPending || !me.data} onClick={() => save.mutate()}>บันทึกการเปลี่ยนแปลง</button>} /><div className="mb-5 grid gap-3 sm:grid-cols-3"><input className="field" placeholder="ค้นหา" value={search} onChange={(e) => setSearch(e.target.value)} /><select className="field" value={category} onChange={(e) => setCategory(e.target.value)}><option value="">ทุกหมวด</option>{categories.data?.map((v) => <option key={v.categoryId} value={v.categoryId}>{v.categoryName}</option>)}</select><label className="flex min-h-11 items-center gap-2 border px-3"><input type="checkbox" checked={selectedOnly} onChange={(e) => setSelectedOnly(e.target.checked)} /> เฉพาะที่เลือก</label></div>{save.error && <ErrorBox error={save.error} />}
    <div className="grid gap-4 md:grid-cols-2">{filtered.map((item) => { const value = draft[item.itemId]; return <article className={`border bg-white ${value?.isActive ? "border-black shadow-[4px_4px_0_#18181b]" : "border-zinc-300"}`} key={item.itemId}><div className="grid grid-cols-[90px_1fr]"><ProductImage name={item.itemName} src={item.imageUrl} /><div className="p-3"><div className="flex justify-between gap-2"><div><p className="font-black">{item.itemName}</p><p className="text-xs text-zinc-500">{item.unit}</p></div><input type="checkbox" checked={value?.isActive ?? false} onChange={(e) => update(item.itemId, { isActive: e.target.checked })} /></div></div></div>{value?.isActive && <div className="grid gap-2 border-t p-3 sm:grid-cols-2"><label className="text-xs font-bold">ขั้นต่ำ<input className="field mt-1" type="number" min="0" value={value.minQty} onChange={(e) => update(item.itemId, { minQty: Number(e.target.value) })} /></label><label className="text-xs font-bold">เป้าหมาย<input className="field mt-1" type="number" min="0" value={value.targetQty} onChange={(e) => update(item.itemId, { targetQty: Number(e.target.value) })} /></label><label className="text-xs font-bold sm:col-span-2">ตำแหน่งปลายทาง<select className="field mt-1" value={value.defaultLocationId} onChange={(e) => update(item.itemId, { defaultLocationId: e.target.value })}><option value="">ยังไม่กำหนด</option>{locations.data?.filter((v) => v.isActive).map((v) => <option key={v.locationId} value={v.locationId}>{v.locationName}</option>)}</select></label><label className="text-xs"><input type="checkbox" checked={value.allowRequest} onChange={(e) => update(item.itemId, { allowRequest: e.target.checked })} /> อนุญาตให้เบิก</label><label className="text-xs"><input type="checkbox" checked={value.requireDailyCount} onChange={(e) => update(item.itemId, { requireDailyCount: e.target.checked })} /> ต้องนับทุกวัน</label></div>}</article>; })}</div>
  </>;
}
