"use client";
import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation, useQuery } from "@tanstack/react-query";
import { useRouter } from "next/navigation";
import { useMemo, useRef, useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { ProductImage } from "@/components/product-image";
import { Empty, ErrorBox, PageHeader } from "@/components/page-kit";
import { get, post } from "@/lib/api";
import type { CreateRequestResult, RequestableItem } from "@/lib/types";
import { useBackpack } from "@/stores/backpack";

const schema = z.object({ note: z.string().max(500) }); type Form = z.infer<typeof schema>;
export default function RequestRoomPage() {
  const router = useRouter(); const query = useQuery({ queryKey: ["requestable-items"], queryFn: () => get<RequestableItem[]>("/requestable-items") }); const bag = useBackpack(); const requestKey = useRef<string | null>(null); const [category, setCategory] = useState(""); const [search, setSearch] = useState(""); const [open, setOpen] = useState(false); const form = useForm<Form>({ resolver: zodResolver(schema), defaultValues: { note: bag.requestNote } });
  const submit = useMutation({ mutationFn: (values: Form) => { requestKey.current ??= crypto.randomUUID(); return post<CreateRequestResult>("/stock-requests", { note: values.note || undefined, items: bag.items.map((v) => ({ itemId: v.itemId, requestedQty: Number(v.requestedQty), unit: v.unit, note: v.note || undefined })) }, { "Idempotency-Key": requestKey.current }); }, onSuccess: (request) => { requestKey.current = null; bag.clear(); router.push(`/inventory/requests/${request.requestId}`); } });
  const categories = useMemo(() => Array.from(new Map((query.data ?? []).map((v) => [v.category?.categoryId ?? "other", v.category?.categoryName ?? "อื่น ๆ"])), ([id, name]) => ({ id, name })), [query.data]); const filtered = (query.data ?? []).filter((v) => (!category || v.category?.categoryId === category) && v.itemName.toLowerCase().includes(search.toLowerCase()));
  return <><PageHeader eyebrow="Gamified stock room" title="แผนที่ห้องสินค้า" description="เลือกห้อง เดินดูของ และใส่รายการที่ต้องการลงกระเป๋าเบิก" /><div className="mb-5 flex gap-3 overflow-x-auto pb-2"><button className={`min-h-16 min-w-28 border border-black px-4 font-black ${!category ? "bg-black text-white" : "bg-white"}`} onClick={() => setCategory("")}>ทุกห้อง</button>{categories.map((v, index) => <button key={v.id} className={`min-h-16 min-w-36 border border-black px-4 text-left font-black ${category === v.id ? "bg-red-600 text-white" : "bg-white"}`} onClick={() => setCategory(v.id)}><span className="block text-xs opacity-60">ROOM {String(index + 1).padStart(2, "0")}</span>{v.name}</button>)}</div><input className="field mb-5" placeholder="ค้นหาของในโกดัง" value={search} onChange={(e) => setSearch(e.target.value)} />
    {query.isError ? <ErrorBox error={query.error} /> : !filtered.length ? <Empty text="ห้องนี้ยังไม่มีสินค้าที่เบิกได้" /> : <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{filtered.map((item) => { const selected = bag.items.some((v) => v.itemId === item.itemId); return <article className={`overflow-hidden bg-white ${selected ? "border-2 border-red-600 shadow-[5px_5px_0_#ef4444]" : "border border-black"}`} key={item.itemId}><ProductImage src={item.imageUrl} name={item.itemName} /><div className="p-3"><p className="font-black">{item.itemName}</p><p className="text-xs text-zinc-500">{item.unit} · Min {item.storeItem.minQty} / Target {item.storeItem.targetQty}</p><button className={`mt-3 w-full ${selected ? "btn-secondary" : "btn-primary"}`} onClick={() => selected ? bag.remove(item.itemId) : bag.add({ itemId: item.itemId, itemName: item.itemName, unit: item.unit })}>{selected ? "เอาออก" : "+ ใส่กระเป๋า"}</button></div></article>; })}</div>}
    <button onClick={() => setOpen(true)} className="fixed bottom-20 right-4 z-30 min-h-14 rounded-full bg-red-600 px-5 font-black text-white shadow-lg lg:bottom-6">กระเป๋าเบิก · {bag.items.length}</button>
    {open && <div className="fixed inset-0 z-50 bg-black/50" onClick={() => setOpen(false)}><aside className="absolute inset-x-0 bottom-0 max-h-[88vh] overflow-auto bg-white p-5 sm:left-auto sm:top-0 sm:w-[460px]" onClick={(e) => e.stopPropagation()}><div className="mb-5 flex justify-between"><h2 className="text-2xl font-black">กระเป๋าเบิกของ</h2><button onClick={() => setOpen(false)}>✕</button></div>{!bag.items.length ? <Empty text="กระเป๋ายังว่าง" /> : <form onSubmit={form.handleSubmit((v) => { if (!submit.isPending) submit.mutate(v); })}><div className="space-y-3">{bag.items.map((v) => <div className="border border-black p-3" key={v.itemId}><div className="flex justify-between"><p className="font-bold">{v.itemName}</p><button type="button" className="text-red-600" onClick={() => bag.remove(v.itemId)}>ลบ</button></div><div className="mt-2 grid grid-cols-[1fr_auto] gap-2"><input aria-label={`จำนวน ${v.itemName}`} className="field" inputMode="decimal" type="number" min="0.01" step="0.01" value={v.requestedQty} onChange={(e) => bag.update(v.itemId, { requestedQty: Number(e.target.value) })} /><span className="self-center text-sm">{v.unit}</span></div><input className="field mt-2" placeholder="หมายเหตุรายการ" value={v.note} onChange={(e) => bag.update(v.itemId, { note: e.target.value })} /></div>)}</div><textarea className="field mt-4" placeholder="หมายเหตุทั้งคำขอ" {...form.register("note")} onChange={(e) => { form.setValue("note", e.target.value); bag.setRequestNote(e.target.value); }} />{submit.error && <div className="mt-4"><ErrorBox error={submit.error} /></div>}<button className="btn-primary mt-4 w-full" disabled={submit.isPending || !bag.items.length || bag.items.some((v) => !Number.isFinite(v.requestedQty) || v.requestedQty <= 0)}>{submit.isPending ? "กำลังส่ง..." : "ส่งคำขอ"}</button></form>}</aside></div>}
  </>;
}
