"use client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { ErrorBox, PageHeader } from "@/components/page-kit";
import { get, post } from "@/lib/api";
import type { Item, Location, Movement } from "@/lib/types";

const schema = z.object({ movementType: z.enum(["RECEIVE", "ISSUE", "TRANSFER", "WASTE", "RETURN", "ADJUSTMENT"]), itemId: z.string().min(1), fromLocationId: z.string(), toLocationId: z.string(), qty: z.coerce.number().positive(), note: z.string(), adjustmentDirection: z.enum(["increase", "decrease"]) }); type Form = z.infer<typeof schema>;
export default function MovementsPage() {
  const client = useQueryClient(); const items = useQuery({ queryKey: ["items"], queryFn: () => get<Item[]>("/items") }); const locations = useQuery({ queryKey: ["locations"], queryFn: () => get<Location[]>("/locations") }); const history = useQuery({ queryKey: ["movements"], queryFn: () => get<Movement[]>("/stock-movements") }); const [filter, setFilter] = useState("");
  const form = useForm<Form>({ defaultValues: { movementType: "RECEIVE", itemId: "", fromLocationId: "", toLocationId: "", qty: 1, note: "", adjustmentDirection: "increase" } }); const type = form.watch("movementType");
  const save = useMutation({ mutationFn: (input: Form) => { const v = schema.parse(input); const item = items.data?.find((i) => i.itemId === v.itemId); return post("/stock-movements", { ...v, unit: item?.unit ?? "" }); }, onSuccess: () => { client.invalidateQueries({ queryKey: ["movements"] }); client.invalidateQueries({ queryKey: ["balances"] }); form.reset({ movementType: "RECEIVE", itemId: "", fromLocationId: "", toLocationId: "", qty: 1, note: "", adjustmentDirection: "increase" }); } });
  const visible = useMemo(() => (history.data ?? []).filter((v) => !filter || v.movementType === filter), [history.data, filter]); const needsFrom = ["ISSUE", "TRANSFER", "WASTE"].includes(type) || (type === "ADJUSTMENT" && form.watch("adjustmentDirection") === "decrease"); const needsTo = ["RECEIVE", "TRANSFER", "RETURN"].includes(type) || (type === "ADJUSTMENT" && form.watch("adjustmentDirection") === "increase");
  return <><PageHeader eyebrow="Stock movement" title="รับเข้าและเคลื่อนไหว" description="ทุกการเปลี่ยนยอดจะสร้าง Movement และอัปเดต Balance" /><div className="grid gap-6 xl:grid-cols-[400px_1fr]"><form className="panel h-fit p-5" onSubmit={form.handleSubmit((v) => save.mutate(v))}><select className="field mb-3" {...form.register("movementType")}>{["RECEIVE", "ISSUE", "TRANSFER", "WASTE", "RETURN", "ADJUSTMENT"].map((v) => <option key={v}>{v}</option>)}</select>{type === "ADJUSTMENT" && <select className="field mb-3" {...form.register("adjustmentDirection")}><option value="increase">เพิ่มยอด</option><option value="decrease">ลดยอด</option></select>}<select className="field mb-3" {...form.register("itemId")}><option value="">เลือกสินค้า</option>{items.data?.filter((v) => v.isActive).map((v) => <option key={v.itemId} value={v.itemId}>{v.itemName} ({v.unit})</option>)}</select>{needsFrom && <select className="field mb-3" {...form.register("fromLocationId")}><option value="">ต้นทาง</option>{locations.data?.filter((v) => v.isActive).map((v) => <option key={v.locationId} value={v.locationId}>{v.locationName}</option>)}</select>}{needsTo && <select className="field mb-3" {...form.register("toLocationId")}><option value="">ปลายทาง</option>{locations.data?.filter((v) => v.isActive).map((v) => <option key={v.locationId} value={v.locationId}>{v.locationName}</option>)}</select>}<input className="field mb-3" type="number" inputMode="decimal" min="0.01" step="0.01" {...form.register("qty")} placeholder="จำนวน" /><textarea className="field mb-3" {...form.register("note")} placeholder="หมายเหตุ" />{save.error && <ErrorBox error={save.error} />}<button className="btn-primary w-full" disabled={save.isPending}>บันทึก Movement</button></form><section><div className="mb-3 flex items-center justify-between"><h2 className="text-xl font-black">ประวัติล่าสุด</h2><select className="field max-w-48" value={filter} onChange={(e) => setFilter(e.target.value)}><option value="">ทุกประเภท</option>{["RECEIVE", "ISSUE", "TRANSFER", "WASTE", "RETURN", "ADJUSTMENT"].map((v) => <option key={v}>{v}</option>)}</select></div>{history.isError ? <ErrorBox error={history.error} /> : <div className="max-h-[650px] overflow-auto border border-black bg-white">{visible.map((v) => <div className="grid grid-cols-[1fr_auto] gap-3 border-b p-3 text-sm" key={v.movementId}><div><p className="font-bold">{items.data?.find((i) => i.itemId === v.itemId)?.itemName || v.itemId}</p><p className="text-zinc-500">{v.movementType} · {v.movementDate} · {v.note}</p></div><p className="font-black">{v.qty} {v.unit}</p></div>)}</div>}</section></div></>;
}
