"use client";
import { useQuery } from "@tanstack/react-query";
import Link from "next/link";
import { useState } from "react";
import { Badge, Empty, ErrorBox, PageHeader } from "@/components/page-kit";
import { get } from "@/lib/api";
import type { StockRequest } from "@/lib/types";

const statuses = ["", "PENDING", "APPROVED", "PARTIAL", "COMPLETED", "REJECTED", "CANCELLED"];
export default function RequestsPage() { const [status, setStatus] = useState(""); const query = useQuery({ queryKey: ["requests", status], queryFn: () => get<StockRequest[]>(`/stock-requests${status ? `?status=${status}` : ""}`) }); return <><PageHeader eyebrow="Request history" title="คำขอเบิกสินค้า" description="ติดตามความคืบหน้าตั้งแต่รออนุมัติจนจ่ายครบ" /><div className="mb-5 flex gap-2 overflow-x-auto">{statuses.map((v) => <button key={v || "ALL"} onClick={() => setStatus(v)} className={`min-h-11 whitespace-nowrap border border-black px-3 text-sm font-bold ${status === v ? "bg-black text-white" : "bg-white"}`}>{v || "ทั้งหมด"}</button>)}</div>{query.isError ? <ErrorBox error={query.error} /> : !query.data?.length ? <Empty text="ไม่พบคำขอ" /> : <div className="space-y-3">{query.data.map((v) => { const progress = v.requestedTotal ? Math.min(100, ((v.issuedTotal ?? 0) / v.requestedTotal) * 100) : 0; return <Link href={`/inventory/requests/${v.requestId}`} key={v.requestId} className="flex flex-col justify-between gap-3 border border-black bg-white p-4 hover:shadow-[4px_4px_0_#18181b] sm:flex-row"><div className="min-w-0 flex-1"><p className="font-black">{v.requestId}</p><p className="text-sm text-zinc-500">{v.requestDate} · {v.itemCount ?? 0} รายการ · จ่าย {v.issuedTotal ?? 0}/{v.requestedTotal ?? 0}</p><div className="mt-2 h-2 max-w-md bg-zinc-200"><div className="h-full bg-red-600" style={{ width: `${progress}%` }} /></div></div><Badge tone={v.requestStatus === "COMPLETED" ? "success" : v.requestStatus === "REJECTED" ? "danger" : "warning"}>{v.requestStatus}</Badge></Link>; })}</div>}</>; }
